/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.comprovei.barcodereader;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static int contents_text=0x7f050000;
        public static int encode_view=0x7f050001;
        public static int possible_result_points=0x7f050002;
        /**  Android standard ICS color 
         */
        public static int result_minor_text=0x7f050003;
        public static int result_points=0x7f050004;
        /**  Android standard ICS color 
         */
        public static int result_text=0x7f050005;
        public static int result_view=0x7f050006;
        public static int status_text=0x7f050007;
        public static int transparent=0x7f050008;
        public static int viewfinder_laser=0x7f050009;
        /**  Android standard ICS color 
         */
        public static int viewfinder_mask=0x7f05000a;
    }
    public static final class dimen {
        /** 
         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static int activity_horizontal_margin=0x7f060002;
        public static int half_padding=0x7f060001;
        public static int standard_padding=0x7f060000;
    }
    public static final class drawable {
        public static int ic_launcher=0x7f020000;
        public static int launcher_icon=0x7f020001;
    }
    public static final class id {
        public static int barcode_image_view=0x7f07000a;
        public static int contents_supplement_text_view=0x7f070011;
        public static int contents_text_view=0x7f070010;
        public static int decode=0x7f070000;
        public static int decode_failed=0x7f070001;
        public static int decode_succeeded=0x7f070002;
        public static int format_text_view=0x7f07000b;
        public static int launch_product_query=0x7f070003;
        public static int meta_text_view=0x7f07000f;
        public static int meta_text_view_label=0x7f07000e;
        public static int preview_view=0x7f070007;
        public static int quit=0x7f070004;
        public static int restart_preview=0x7f070005;
        public static int result_button_view=0x7f070012;
        public static int result_view=0x7f070009;
        public static int return_scan_result=0x7f070006;
        public static int status_view=0x7f070013;
        public static int time_text_view=0x7f07000d;
        public static int type_text_view=0x7f07000c;
        public static int viewfinder_view=0x7f070008;
    }
    public static final class layout {
        public static int main=0x7f030000;
    }
    public static final class raw {
        public static int beep=0x7f040000;
    }
    public static final class string {
        public static int app_name=0x7f080000;
        public static int cancel=0x7f080002;
        public static int msg_bulk_mode_scanned=0x7f080003;
        public static int msg_camera_framework_bug=0x7f080004;
        public static int msg_default_format=0x7f080005;
        public static int msg_default_meta=0x7f080006;
        public static int msg_default_status=0x7f080007;
        public static int msg_default_time=0x7f080008;
        public static int msg_default_type=0x7f080009;
        public static int ok=0x7f080001;
    }
    public static final class style {
        /** 
        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static int AppBaseTheme=0x7f090002;
        public static int BarcodeTheme=0x7f090003;
        public static int ResultButton=0x7f090000;
        public static int ShareButton=0x7f090001;
    }
}
